### ISSUE TITLE
add windows

### ISSUE THREAD

**Issue by xoviat** [conda-forge/sed-feedstock#16]
The windows package is available on chocolatey. It can simply be downloaded and repackaged.

**Comment by isuruf** [comment]
We have it packaged as `m2-sed`

**Comment by xoviat** [comment]
it's not listed on the website: https://conda-forge.org/feedstock-outputs/

do you also have gawk?

**Comment by isuruf** [comment]
Yes, there's `m2-gawk`. `m2` packages are special and might need special handling in that list

**Comment by xoviat** [comment]
is there a list of m2 packages?

**Comment by isuruf** [comment]
https://github.com/conda-forge/msys2-recipes/tree/master/msys2

**Comment by xoviat** [comment]
thx
